default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 111 
  host: localhost

development:
  <<: *default
  database: kurss_development

test:
  <<: *default
  database: kurss_test

production:
  <<: *default
  database: kurss_production
  username: kurss
  password: <%= ENV["KURSS_DATABASE_PASSWORD"] %>